### ISSUE TITLE
pre-launch checklist

### ISSUE THREAD

**Issue by jnewbery** [chaincodelabs/podcast-website#1]
- [x] make sure that @adamjonas and @Caralie are happy to have their twitter handles linked from the 'about' page.
- [x] embed anchor.fm player and link to download episode to the Pieter post.
- [x] set up netlify/github pages to host
- [x] configure dns record for `podcast.chaincode.com`
